using System.Net;
using System.Text.Json;
using EmployeeManager.Application.Common.Exceptions;
using EmployeeManager.WepApi.Dto.Common;
using FluentValidation;

namespace EmployeeManager.WepApi.Middleware;

class CustomExceptionHandlerMiddleware
{
    private readonly RequestDelegate _next;

    public CustomExceptionHandlerMiddleware(RequestDelegate next) =>
        _next = next;

    public async Task Invoke(HttpContext context)
    {
        try
        {
            await _next(context);
        }
        catch (Exception exception)
        {
            await HandleExceptionAsync(context, exception);
        }
    }

    private Task HandleExceptionAsync(HttpContext context, Exception exception)
    {
        var code = HttpStatusCode.InternalServerError;
        var result = string.Empty;
        switch (exception)
        {
            case ValidationException validationException:
                code = HttpStatusCode.BadRequest;
                var errors = validationException.Errors.Select(x => new ValidationError()
                {
                    PropertyName = x.PropertyName,
                    ErrorMessage = x.ErrorMessage
                });
                result = JsonSerializer.Serialize(errors);
                break;
            case NotFoundException:
                code = HttpStatusCode.NotFound;
                break;
        }

        context.Response.ContentType = "application/json";
        context.Response.StatusCode = (int)code;

        if (result == string.Empty)
        {
            result = JsonSerializer.Serialize(new { errpr = exception.Message });
        }

        return context.Response.WriteAsync(result);
    }
}